// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mrls
arma::mat mrls(const arma::vec& y, const arma::mat& x, const int& start, const arma::mat& rhoseq, const arma::vec& refitseqby, const double& eps, const double& lambda);
RcppExport SEXP _VSCodeRcppDemo_mrls(SEXP ySEXP, SEXP xSEXP, SEXP startSEXP, SEXP rhoseqSEXP, SEXP refitseqbySEXP, SEXP epsSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type rhoseq(rhoseqSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type refitseqby(refitseqbySEXP);
    Rcpp::traits::input_parameter< const double& >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(mrls(y, x, start, rhoseq, refitseqby, eps, lambda));
    return rcpp_result_gen;
END_RCPP
}
// calc_sum
double calc_sum(NumericVector x);
RcppExport SEXP _VSCodeRcppDemo_calc_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_sum(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VSCodeRcppDemo_mrls", (DL_FUNC) &_VSCodeRcppDemo_mrls, 7},
    {"_VSCodeRcppDemo_calc_sum", (DL_FUNC) &_VSCodeRcppDemo_calc_sum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_VSCodeRcppDemo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
